### ISSUE TITLE
Support for Herochat channel variables and channel specifc formatting

### ISSUE THREAD

**Issue by AaronMcHale** [cnaude/PurpleBungeeIRC#1]
Hi, first of all thank you for making this plugin for Bungee, it may prove to be the missing link in our chat setup.

Would it be possible to add support for the %HEROCOLOR% %HERONICK% variables, as well as for the ability to change message formatting per HC Channel, in the same way that you can with PurpleIRC

  irc-hero-channels:
    Global: ''
  irc-hero-action-channels:
    Global: ''
  hero-channels:
    Global: ''
  hero-action-channels:
    Global: ''

Thank you and much appreciated
Aaron

**Comment by cnaude** [comment]
For %HEROCOLOR% and %HERONICK% please try the latest builds.
http://h.cnaude.org:8081/job/HerochatBungeeBridge-Bukkit/6/
http://h.cnaude.org:8081/job/PurpleBungeeIRC/17/

**Comment by AaronMcHale** [comment]
Hi thanks for the update, I am now receiving exceptions in console when someone in IRC talks

> [20:16:50 WARN]: Could not pass incoming plugin message to BungeeChatClient v0.4-6
> java.lang.NoClassDefFoundError: com/herochat/Herochat
>        at com.jumanjicraft.BungeeChatClient.BungeeChatListener.onPluginMessageReceived(BungeeChatListener.java:71) ~[?:?]
>        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:2065) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.PacketPlayInCustomPayload.a(SourceFile:55) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.PacketPlayInCustomPayload.a(SourceFile:8) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_60]
>        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_60]
>        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
>        at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]

Note that I just switched from using original HerochatBungeeBridge plugin to the updated one that you are working on.

Thanks
Aaron

**Comment by cnaude** [comment]
What version of HeroChat are you running on your Spigot server?

**Comment by AaronMcHale** [comment]
This one:

> >version Herochat
> [20:48:25 INFO]: Herochat version 5.6.7-SNAPSHOT
> [20:48:25 INFO]: Chat channel system
> [20:48:25 INFO]: Website: http://www.herocraftonline.com
> [20:48:25 INFO]: Authors: DThielke, Sleaker and Kainzo

**Comment by cnaude** [comment]
Here is a special build for Spigot 1.8 and Herochat 5.6.7.
http://h.cnaude.org:8081/job/HerochatBungeeBridge-Bukkit/10/

**Comment by AaronMcHale** [comment]
Hi thanks, that build works, although the color and nick variables aren't being filtered out, an extract from my config is:

>  # Message templates for IRC to Herochat messages
>  irc-hero-action: '%HEROCOLOR%#%HERONICK%&f \* [&bIRC&r] &b%NAME%&r %MESSAGE%'
>  irc-hero-chat: '%HEROCOLOR%#%HERONICK%&f [&bIRC&r] &b%PLAYERPREFIX% %NAME%&r:
>    %MESSAGE%'
