### ISSUE TITLE
Upgrade to waterfall 1.16.1 breaks Purplebungeeirc colorconverter

### ISSUE THREAD

**Issue by sorcererno** [cnaude/PurpleBungeeIRC#13]
[11:06:12] [main/WARN]: Exception encountered when loading plugin: PurpleBungeeIRC
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/cnaude/purpleirc/Utilities/ColorConverter.addIrcColorMap(Ljava/lang/String;Ljava/lang/String;)V @154: invokevirtual
  Reason:
    Type 'net/md_5/bungee/api/ChatColor' (current frame, stack[1]) is not assignable to 'java/lang/Enum'
  Current Frame:
    bci: @154
    flags: { }
    locals: { 'com/cnaude/purpleirc/Utilities/ColorConverter', 'java/lang/String', 'java/lang/String', 'net/md_5/bungee/api/ChatColor' }
    stack: { 'java/util/EnumMap', 'net/md_5/bungee/api/ChatColor', 'java/lang/String' }
  Bytecode:
    0000000: 2bb6 003a b800 3b4e 2c12 3cb6 003d 9900
    0000010: 3b2a b400 052d b600 3e99 0030 2ab4 000d
    0000020: bb00 2159 b700 2212 3fb6 0024 2cb6 0024
    0000030: 1226 b600 242b b600 24b6 0027 b600 282a
    0000040: b400 052d b600 4057 b1a7 0020 3a04 2ab4
    0000050: 000d bb00 2159 b700 2212 42b6 0024 2bb6
    0000060: 0024 b600 27b6 0043 b12d c600 342a b400
    0000070: 0dbb 0021 59b7 0022 123f b600 242b b600
    0000080: 2412 26b6 0024 2cb6 0024 b600 27b6 0028
    0000090: 2ab4 0005 2d2a 2cb7 0044 b600 4557 b1  
  Exception Handler Table:
    bci [0, 72] => handler: 76
  Stackmap Table:
    append_frame(@73,Object[#176])
    full_frame(@76,{Object[#169],Object[#154],Object[#154]},{Object[#177]})
    append_frame(@105,Object[#176])
    same_frame(@158)

	at com.cnaude.purpleirc.PurpleIRC.loadConfig(PurpleIRC.java:392) ~[?:?]
	at com.cnaude.purpleirc.PurpleIRC.onEnable(PurpleIRC.java:180) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366]

**Comment by beauchette** [comment]
I have the exact same problem for the same exact upgrade.

**Comment by sorcererno** [comment]
Thanks a bunch!
