### ISSUE TITLE
PurpleBungeeIRC problem for Waterfall with MC version >=1.18

### ISSUE THREAD

**Issue by gotteweiss** [cnaude/PurpleBungeeIRC#17]
When we switched to new Waterfall version with Minecraft 1.18 server support, we've stumbled upon a following problem. The plugin starts, yet it throws an error:
```
[17:23:46] [PurpleBungeeIRC Pool Thread #5/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@278667fd, id=9, owner=com.cnaude.purpleirc.PurpleIRC@2c6aed22, task=com.cnaude.purpleirc.Purpl
eBot$3@456ae46a, delay=0, period=0, running=true) encountered an exception
java.lang.NoSuchFieldError: WHITESPACE
        at org.pircbotx.Utils.tokenizeLine(Utils.java:106) ~[?:?]
        at org.pircbotx.InputParser.handleLine(InputParser.java:307) ~[?:?]
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:282) ~[?:?]
        at org.pircbotx.PircBotX.connect(PircBotX.java:242) ~[?:?]
        at org.pircbotx.PircBotX.startBot(PircBotX.java:155) ~[?:?]
        at com.cnaude.purpleirc.PurpleBot$3.run(PurpleBot.java:409) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
After that, it stops and nothing happens. Config remained unchanged since 1.17, and it worked perfectly for that version.

**Comment by NinCollin** [comment]
Also confirmed for regular BungeeCord (BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:6963156:1658)
