### ISSUE TITLE
Illegal State Exception on Chat Message

### ISSUE THREAD

**Issue by Omeryl** [cnaude/PurpleBungeeIRC#3]
Although it still works, getting this every time a chat message is processed minecraft-side (Game->IRC) is slightly annoying:

```
03:17:24 [SEVERE] May 15, 2015 3:17:24 AM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@373a66a6, receiver=Eliz), cancelled=false, tag=BungeeChat, data=[0, 6, 71, 108, 111, 98, 97, 108, 0, 23, -62, -89, 50, 91, 71, 93, 32, -62, -89, 102, 69, 108, 105, 122, -62, -89, 50, 58, 32, 116, 101, 115, 116, 0, 4, 69, 108, 105, 122]) to listener com.cnaude.purpleirc.GameListeners.GamePluginMessageListener@2fc0cc3
java.lang.IllegalStateException: java.io.EOFException
    at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:330)
    at com.cnaude.purpleirc.ChatMessage.<init>(ChatMessage.java:25)
    at com.cnaude.purpleirc.GameListeners.GamePluginMessageListener.receievePluginMessage(GamePluginMessageListener.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:222)
    at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:62)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
    at java.io.DataInputStream.readUTF(DataInputStream.java:589)
    at java.io.DataInputStream.readUTF(DataInputStream.java:564)
    at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:328)
    ... 34 more
```

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleBungeeIRC/39/

**Comment by Omeryl** [comment]
Forgot to state this was fixed, thanks.
