### ISSUE TITLE
Error: Broken pipe

### ISSUE THREAD

**Issue by jesusango** [cnaude/PurpleBungeeIRC#4]
Hi, sorry if this is a stupid question, but when people chat in the server, the server say this error, with debug mode:

I have Unrealircd V: 3.4 installed, and the lastest version of your plugin.

01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] Player Sandrita_Chan has permission irc.message.gamechat
01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] [game-chat] => #minecraft-test => Hi :)
01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] Tokenizing Sandra
01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] [P]Raw message: [Â§2%SERVER%Â§r] <%NAME%> %MESSAGE%
01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] Entering aysncIRCMessage
01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] [0]: queueAndSend message detected
01:22:26 [INFO] [PurpleBungeeIRC] [DEBUG] [blockingIRCMessage] About to send IRC message to #minecraft-test
01:22:26 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@508dec2b, id=1, owner=com.cnaude.purpleirc.PurpleIRC@2c1b194a, task=com.cnaude.purpleirc.IRCMessageQueueWatcher$1@5efa40fe, delay=0, period=1000, running=true) encountered an exception
java.lang.RuntimeException: Couldn't pause thread for message delay
    at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:76)
    at org.pircbotx.output.OutputRaw.rawLineSplit(OutputRaw.java:129)
    at org.pircbotx.output.OutputRaw.rawLineSplit(OutputRaw.java:116)
    at org.pircbotx.output.OutputIRC.message(OutputIRC.java:138)
    at com.cnaude.purpleirc.PurpleBot.blockingIRCMessage(PurpleBot.java:404)
    at com.cnaude.purpleirc.IRCMessageQueueWatcher.queueAndSend(IRCMessageQueueWatcher.java:42)
    at com.cnaude.purpleirc.IRCMessageQueueWatcher.access$000(IRCMessageQueueWatcher.java:12)
    at com.cnaude.purpleirc.IRCMessageQueueWatcher$1.run(IRCMessageQueueWatcher.java:30)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Exception encountered when writing to socket
    at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:318)
    at org.pircbotx.Utils.sendRawLineToServer(Utils.java:89)
    at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:73)
    ... 11 more
Caused by: java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
    at java.io.Writer.write(Writer.java:157)
    at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:314)
    ... 13 more

**Comment by cnaude** [comment]
Please try the latest dev build: http://h.cnaude.org:8081/job/PurpleBungeeIRC/44/artifact/target/PurpleBungeeIRC-0.1.44.jar
